<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="China Standard Time">
<General productName="QuickTest Professional" productVer="9.5" os="Windows XP" host="LTE-7PN383X"><DocLocation><![CDATA[\\10.68.143.208\iAUTO\QTPScripts95_TDD_Prod\SiteMan\SiteMan_MenuOperation]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[SiteMan_MenuOperation]]></DName>
<Res><![CDATA[qtp_log20120409175224]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>The function</u>:</b> Recovery_DeleteJavaProcess<br><b><u>is called from multiple sources</u>:</b><dd><b>Scenario</b> Connect_UnexpectedErrorInConnectionToBTS <b>defined in</b> SiteMan\SitemMan_Recover.qrs <b>calls this function from</b> \\10.68.143.208\iAUTO\QTPScripts95_TDD_Dev\SiteMan\SiteMan.vbs<b>Scenario</b> Connect_CannotReconnectToLTEBTS <b>defined in</b> SiteMan\SitemMan_Recover.qrs <b>calls this function from</b> \\10.68.143.208\iAUTO\QTPScripts95_TDD_Prod\SiteMan\SiteMan.vbs</dd></dl></div></SPAN>]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:49]]></Time>
<NodeArgs eType="Replay" icon="3" nRep="6" status="Warning" nType="Recovery" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[<SPAN class=text><div align=left><dl><b><u>The function</u>:</b> Recovery_Login<br><b><u>is called from multiple sources</u>:</b><dd><b>Scenario</b> Connect_UnexpectedErrorInConnectionToBTS <b>defined in</b> SiteMan\SitemMan_Recover.qrs <b>calls this function from</b> \\10.68.143.208\iAUTO\QTPScripts95_TDD_Dev\SiteMan\SiteMan.vbs<b>Scenario</b> Connect_CannotReconnectToLTEBTS <b>defined in</b> SiteMan\SitemMan_Recover.qrs <b>calls this function from</b> \\10.68.143.208\iAUTO\QTPScripts95_TDD_Prod\SiteMan\SiteMan.vbs</dd></dl></div></SPAN>]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:49]]></Time>
<NodeArgs eType="Replay" icon="3" nRep="7" status="Warning" nType="Recovery" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T5" iterID="1" >
<Action rID="T6">
<AName><![CDATA[Action1]]></AName>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ JavaDialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="12" >
<Disp><![CDATA[[ JavaDialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ 861 - Local connection - BTS Site Manager ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[[ 861 - Local connection - BTS Site Manager ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ 861 - Local connection - BTS Site Manager ].Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[[ 861 - Local connection - BTS Site Manager ].Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ 861 - Local connection - BTS Site Manager ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="17" >
<Disp><![CDATA[[ 861 - Local connection - BTS Site Manager ].Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Software ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Software ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ JavaMenu ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:50]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="20" >
<Disp><![CDATA[[ JavaMenu ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Update SW to BTS Site... ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[[ Update SW to BTS Site... ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ JavaMenu ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[[ JavaMenu ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Update SW to BTS Site ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="24" >
<Disp><![CDATA[[ Update SW to BTS Site ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ File: ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="25" >
<Disp><![CDATA[[ File: ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ File: ].GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[0]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="27" >
<Disp><![CDATA[[ File: ].GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ File: ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Browse..."]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:51]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="29" >
<Disp><![CDATA[[ File: ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Select Build Descriptor ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:53]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="30" >
<Disp><![CDATA[[ Select Build Descriptor ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ File name: ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["D:\BTS_SW\LNT2.0_ENB_9308_035_00_release_BTSSM_downloadable_wo_images.zip"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:53]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="32" >
<Disp><![CDATA[[ File name: ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Open ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:53]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="34" >
<Disp><![CDATA[[ Open ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:54]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="35" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:56]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="36" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:57]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="37" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:58]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="38" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:52:59]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="39" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:01]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="40" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:02]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="41" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Update ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:03]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="42" >
<Disp><![CDATA[[ Update ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Update ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:03]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="44" >
<Disp><![CDATA[[ Update ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="47" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="50" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="53" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="56" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="59" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="62" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="65" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="68" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="71" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="74" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="77" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="80" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="83" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="86" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="89" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="92" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="95" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="98" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="101" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="104" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="107" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="110" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="113" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ View Report ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:06]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="114" >
<Disp><![CDATA[[ View Report ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:07]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="117" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:07]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="120" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="123" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="126" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="129" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="132" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="135" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="138" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="141" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="144" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="147" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="150" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="153" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="156" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="159" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:08]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="162" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="165" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="168" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="171" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="174" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="177" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="180" >
<Disp><![CDATA[[ JavaStaticText ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="183" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ View Report ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:09]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="184" >
<Disp><![CDATA[[ View Report ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[[ JavaButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/9/2012 - 17:53:10]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="187" >
<Disp><![CDATA[[ JavaButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj plainTxt="False" ><![CDATA[[ JavaStaticText ].Exist]]></Obj>