<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="China Standard Time">
<General productName="QuickTest Professional" productVer="9.5" os="Windows XP" host="LTE-7PN383X"><DocLocation><![CDATA[\\10.68.143.208\iAUTO\QTPScripts95_TDD_Prod\SiteMan\InstallSeMApplication]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[InstallSeMApplication]]></DName>
<Res><![CDATA[qtp_log20120428173748]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ JavaWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:14]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="10" >
<Disp><![CDATA[[ JavaWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ JavaWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:14]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="12" >
<Disp><![CDATA[[ JavaWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Open File - Security Warning ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:18]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ Open File - Security Warning ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Run ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:18]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="14" >
<Disp><![CDATA[[ Run ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Run ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:18]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="16" >
<Disp><![CDATA[[ Run ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:18]]></Time>
<NodeArgs eType="Replay" icon="6" nRep="18" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ WinButton ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:59]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="24" status="Warning" >
<Disp><![CDATA[[ WinButton ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ WinButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ WinButton ]" object's parent "[ Dialog ]" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:59]]></Time>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Title = Open File - Security Warning<br>]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:59]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="26" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="25" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ WinButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;[ WinButton ]&quot; object's parent &quot;[ Dialog ]&quot; (class Dialog). Verify that parent properties match an object currently displayed in your application.<BR>Function file: \\10.68.143.208\iAUTO\QTPScripts95_TDD_Prod\SiteMan\SiteMan.vbs<BR>Line (6298): &quot;				   Dialog(&quot;title:=Open File - Security Warning&quot;).WinButton(&quot;text:=.*Run&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/28/2012 - 17:38:59]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="27" status="Failed" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:00]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="28" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Introduction(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:00]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="29" >
<Disp><![CDATA[[ Introduction(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:01]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="30" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ License Agreement(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:01]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="31" >
<Disp><![CDATA[[ License Agreement(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:01]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="32" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Next ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:01]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="34" >
<Disp><![CDATA[[ Next ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:02]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="35" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ License Agreement(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:02]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[[ License Agreement(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ I accept the terms of the License Agreement ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:02]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="37" >
<Disp><![CDATA[[ I accept the terms of the License Agreement ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ I accept the terms of the License Agreement ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:02]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="39" >
<Disp><![CDATA[[ I accept the terms of the License Agreement ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:03]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="40" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Installation Type(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:03]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="41" >
<Disp><![CDATA[[ Installation Type(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:03]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="42" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Next ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:03]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="44" >
<Disp><![CDATA[[ Next ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:04]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="45" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Installation Type(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:04]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="46" >
<Disp><![CDATA[[ Installation Type(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ ZeroGn8 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="47" >
<Disp><![CDATA[[ ZeroGn8 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ ZeroGn8 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:05]]></Time>
<NodeArgs eType="Replay" icon="12" nRep="49" >
<Disp><![CDATA[[ ZeroGn8 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:06]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="50" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:06]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="51" >
<Disp><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:06]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="52" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Next ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:06]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="54" >
<Disp><![CDATA[[ Next ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:07]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="55" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:07]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="56" >
<Disp><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:07]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="57" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Next ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:07]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="59" >
<Disp><![CDATA[[ Next ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:08]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="60" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:08]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="61" >
<Disp><![CDATA[[ Pre-Installation Summary(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Install ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:08]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="62" >
<Disp><![CDATA[[ Install ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Install ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:08]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="64" >
<Disp><![CDATA[[ Install ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:09]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="65" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:09]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="66" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:09]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="67" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:10]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="68" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:10]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="69" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:10]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="70" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:11]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="71" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:11]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:11]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="73" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:12]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="74" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:12]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="75" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:12]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="76" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:13]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="77" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:13]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="78" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:13]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="79" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:14]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="80" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:14]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="81" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:14]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="82" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:15]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="83" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:15]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="84" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:15]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="85" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:16]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="86" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:16]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="87" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:16]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="88" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:17]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="89" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:17]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="90" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:17]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="91" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:18]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="92" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:18]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="93" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:18]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="94" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:19]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="95" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:19]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="96" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:19]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="97" >
<Disp><![CDATA[[ Next ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:21]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="98" >
<Disp><![CDATA[[ BTS Site Manager LNT2.0 (2.0.692) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[[ Completed(st) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:21]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="99" >
<Disp><![CDATA[[ Completed(st) ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj plainTxt="False" ><![CDATA[[ Next ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2012 - 17:39:21]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="100" >